### ISSUE TITLE
possible to not use a screenshot capture for the "contentView"?

### ISSUE THREAD

**Issue by TiagoVeloso** [MortimerGoro/MGSwipeTableCell#154]
When using this component I've noticed that it takes a screenshot of my cell and then uses an image view to swipe left or right.

Is it possible to accomplish the same behaviour without the image capture?

**Comment by MortimerGoro** [comment]
Hi,

MGSwipeTableCell creates a layer copy of the underlying cell content. I tried to transform the original layer, it worked like a charm on iOS 7, but not on iOS 6 & iOS 8, the internals of those version don't allow cell or layer transformations. I also tried to override the contentView property, it works with manually added views but it has problem with autolayout constraints. So the layer copy is the safest way to go to avoid a lot of hacking...

In order to support animated contentViews I added an optional to use swipeContentView property in the latest version. If you add your views to this one instead of to the normal cell.contentView, your animations will work while swipping because they are real views (not a screenshot). You can combine both contentView and swipeContentView. MGSwipeTableCell automatically places swipeContentView as a contentView subview when needed.
