### ISSUE TITLE
If animation in cell, when swiping animation will stop

### ISSUE THREAD

**Issue by zon7** [MortimerGoro/MGSwipeTableCell#175]
I have a cell with an animation, like an equalizer.
The animation plays nice, till i start the swipe. in that moment, the animation stops till i hide the buttons again.

**Comment by MortimerGoro** [comment]
Hi,

I have added an optional to use swipeContentView property. If you add your views to this one instead of to the normal cell.contentView, your animations will work while swipping. You can combine both contentView and swipeContentView. MGSwipeTableCell automatically places swipeContentView as a contentView subview when needed.

MGSwipeTableCell creates a layer copy of the underlying cell content. I tried to transform the original layer, it worked like a charm on iOS 7, but not on iOS 8 & 9, the internals of those version don't allow cell or layer transformations. I also tried to override the contentView property, it works with manually added views but it has problem with autolayout constraints. So the layer copy is the safest way to go to avoid a lot of hacking...
