### ISSUE TITLE
Crash Info !

### ISSUE THREAD

**Issue by Yoowait** [MortimerGoro/MGSwipeTableCell#189]
Crash happened while I swipe the cell on iOS 8.3  in the version of MGSwipeTableCell 1.5.4

Bur it run well in iOS 9.2  1.5.4  and IOS 8.3 1.5.3

**Comment by MarshalGeazipp** [comment]
I experienced this crash, too. 
The problem occurs in the method fixRegionAndAccesoryViews in the class MGSwipeTableCell, and the cause is that [UIView userInterfaceLayoutDirectionForSemanticContentAttribute:self.semanticContentAttribute] is called although this API method is only available in iOS 9+, not in iOS 8!

**Comment by MortimerGoro** [comment]
Fixed in 1.5.5 ;)
