### ISSUE TITLE
How to use this class in swift?

### ISSUE THREAD

**Issue by Reza-Rg** [MortimerGoro/MGSwipeTableCell#19]
How to use this class in swift?

**Comment by grantkemp** [comment]
Thanks guys, we should add this to readme.

**Comment by Reza-Rg** [comment]
Thanks for your reply! I implemented this library in my swift project.

**Comment by MHX792** [comment]
I have a CustomCell class that inherits from MGSwipeTableCell:

    class CustomCell: MGSwipeTableCell {
    // properities
    }

These are the settings for the prototype cell in Main.storyboard:

![screen shot 2015-04-26 at 15 50 15](https://cloud.githubusercontent.com/assets/12123471/7337496/0c28d3d0-ec2c-11e4-930d-b4a4ae9e80f8.png)

![screen shot 2015-04-26 at 15 50 21](https://cloud.githubusercontent.com/assets/12123471/7337497/0f350cf6-ec2c-11e4-983e-22517aab015d.png)

I've got this in ViewController.swift:

```
    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCellWithIdentifier("Cell", forIndexPath: indexPath) as! CustomCell
        
        let deleteButton = MGSwipeButton(title: "Delete", backgroundColor: UIColor.redColor(), callback: {
            (sender: MGSwipeTableCell!) -> Bool in
            // do Stuff
            return true
        })
        cell.leftButtons = [deleteButton]

        cell.textLabel?.text = arr[indexPath.row]
        return cell
    }
```
Building fails and I get these error messages: 

![screen shot 2015-04-26 at 15 45 06](https://cloud.githubusercontent.com/assets/12123471/7337478/8f32df10-ec2b-11e4-982f-a89921f9da45.png)

When CustomCell class inherits from UITableViewCell the errors go away:

    class CustomCell: UITableViewCell {
    // properities
    }

Note that I have to outcomment `let deleteButton = ...` and `cell.leftButtons = [deleteButton]` for it to work, since it doesn't inherit from MGSwipeTableCell anymore.

I think demo project with a sample swift integration would be really nice!

**Comment by sravich** [comment]
Whats the line we should be putting into our pod file? Sorry I am new to this is it
pod "MGSwipeTableCell"

**Comment by werediver** [comment]
Important note: if you use Cocoapods with `use_frameworks!` option to install MGSwipeTableCell as a dynamic framework, you don't need the bridging header file. Instead you should use `import MGSwipeTableCell` in Swift code.
